package com.example.services.auth

import android.content.Context
import android.util.Log
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialCancellationException
import androidx.credentials.exceptions.GetCredentialException
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.firebase.FirebaseApp
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.FirebaseUser
import com.google.firebase.auth.GoogleAuthProvider
import com.google.firebase.auth.userProfileChangeRequest
import kotlinx.coroutines.tasks.await
import java.security.MessageDigest
import java.util.UUID

object FirebaseAuthHelper {
    private const val TAG = "FirebaseAuthHelper"

    /**
     * Checks if Firebase is initialized in this application.
     */
    fun isFirebaseAvailable(context: Context): Boolean {
        return try {
            FirebaseApp.getApps(context).isNotEmpty()
        } catch (e: Exception) {
            false
        }
    }

    /**
     * Retrieves the default Web Client ID generated by google-services plugin from google-services.json.
     */
    fun getWebClientId(context: Context): String? {
        return try {
            val resId = context.resources.getIdentifier("default_web_client_id", "string", context.packageName)
            if (resId != 0) {
                val clientId = context.getString(resId)
                if (clientId.isNotBlank()) clientId else null
            } else {
                null
            }
        } catch (e: Exception) {
            null
        }
    }

    /**
     * Creates a new user with Email and Password in Firebase Auth.
     */
    suspend fun signUpWithEmail(
        email: String,
        pass: String,
        displayName: String
    ): Result<FirebaseUser> {
        return try {
            val auth = FirebaseAuth.getInstance()
            val authResult = auth.createUserWithEmailAndPassword(email.trim(), pass.trim()).await()
            val user = authResult.user ?: throw IllegalStateException("User creation failed, no user returned.")
            
            if (displayName.isNotBlank()) {
                try {
                    val profileUpdates = userProfileChangeRequest {
                        this.displayName = displayName.trim()
                    }
                    user.updateProfile(profileUpdates).await()
                } catch (e: Exception) {
                    Log.w(TAG, "Failed to update user profile display name: ${e.message}")
                }
            }
            Result.success(user)
        } catch (e: Exception) {
            Log.e(TAG, "Sign up error", e)
            Result.failure(e)
        }
    }

    /**
     * Signs in an existing user with Email and Password in Firebase Auth.
     */
    suspend fun signInWithEmail(
        email: String,
        pass: String
    ): Result<FirebaseUser> {
        return try {
            val auth = FirebaseAuth.getInstance()
            val authResult = auth.signInWithEmailAndPassword(email.trim(), pass.trim()).await()
            val user = authResult.user ?: throw IllegalStateException("Sign in failed, no user returned.")
            Result.success(user)
        } catch (e: com.google.firebase.auth.FirebaseAuthInvalidCredentialsException) {
            Log.w(TAG, "Invalid credentials for sign in: ${e.message}")
            Result.failure(
                IllegalStateException("Incorrect password or email. If you haven't created an account yet, tap 'Create Account' below.")
            )
        } catch (e: com.google.firebase.auth.FirebaseAuthInvalidUserException) {
            Log.w(TAG, "No account found: ${e.message}")
            Result.failure(
                IllegalStateException("No account found with this email. Tap 'Create Account' to sign up first.")
            )
        } catch (e: Exception) {
            Log.e(TAG, "Sign in error: ${e.message}")
            val msg = e.localizedMessage ?: "Sign in failed. Please check your credentials and internet connection."
            Result.failure(IllegalStateException(msg))
        }
    }

    /**
     * Sends a password reset email to the specified address.
     */
    suspend fun sendPasswordReset(email: String): Result<Unit> {
        return try {
            val auth = FirebaseAuth.getInstance()
            auth.sendPasswordResetEmail(email.trim()).await()
            Result.success(Unit)
        } catch (e: Exception) {
            Log.e(TAG, "Password reset error", e)
            Result.failure(e)
        }
    }

    /**
     * Launches Android CredentialManager to sign in with Google and links the token with Firebase Auth.
     */
    suspend fun signInWithGoogle(context: Context): Result<FirebaseUser> {
        return try {
            val webClientId = getWebClientId(context)
            if (webClientId.isNullOrBlank()) {
                return Result.failure(
                    IllegalStateException("Firebase Web Client ID not found. Please ensure google-services.json is present in app/ directory.")
                )
            }

            val credentialManager = CredentialManager.create(context)
            val rawNonce = UUID.randomUUID().toString()
            val bytes = rawNonce.toByteArray()
            val md = MessageDigest.getInstance("SHA-256")
            val digest = md.digest(bytes)
            val hashedNonce = digest.fold("") { str, it -> str + "%02x".format(it) }

            val googleIdOption = GetGoogleIdOption.Builder()
                .setFilterByAuthorizedAccounts(false)
                .setServerClientId(webClientId)
                .setAutoSelectEnabled(false)
                .setNonce(hashedNonce)
                .build()

            val request = GetCredentialRequest.Builder()
                .addCredentialOption(googleIdOption)
                .build()

            val response = credentialManager.getCredential(
                request = request,
                context = context
            )

            val credential = response.credential
            if (credential is CustomCredential && credential.type == GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL) {
                val googleIdTokenCredential = GoogleIdTokenCredential.createFrom(credential.data)
                val idToken = googleIdTokenCredential.idToken
                
                val firebaseCredential = GoogleAuthProvider.getCredential(idToken, null)
                val authResult = FirebaseAuth.getInstance().signInWithCredential(firebaseCredential).await()
                val user = authResult.user ?: throw IllegalStateException("Firebase credential sign-in returned null user.")
                Result.success(user)
            } else {
                Result.failure(IllegalStateException("Unexpected credential type: ${credential.type}"))
            }
        } catch (e: GetCredentialCancellationException) {
            Log.d(TAG, "User cancelled Google Sign-In")
            Result.failure(e)
        } catch (e: androidx.credentials.exceptions.NoCredentialException) {
            Log.i(TAG, "No Google credentials available on this device: ${e.message}")
            Result.failure(
                IllegalStateException("No Google account found on this device. Please sign in with Email & Password or add a Google account in device Settings.")
            )
        } catch (e: GetCredentialException) {
            Log.w(TAG, "Credential Manager message: ${e.message}")
            val msg = if (e.message?.contains("No credentials", ignoreCase = true) == true) {
                "No Google account found on this device. Please sign in with Email & Password or add a Google account in device Settings."
            } else {
                e.message ?: "Google Sign-In failed on this device."
            }
            Result.failure(IllegalStateException(msg))
        } catch (e: Exception) {
            Log.e(TAG, "Google Sign-In failed", e)
            Result.failure(e)
        }
    }

    /**
     * Retrieves the current authenticated Firebase User, if any.
     */
    fun getCurrentUser(): FirebaseUser? {
        return try {
            FirebaseAuth.getInstance().currentUser
        } catch (e: Exception) {
            null
        }
    }

    /**
     * Signs out of Firebase Auth.
     */
    fun signOut() {
        try {
            FirebaseAuth.getInstance().signOut()
        } catch (e: Exception) {
            Log.e(TAG, "Sign out error", e)
        }
    }
}
