package com.example.core.localization

enum class AppLanguage(val code: String, val displayName: String) {
    ENGLISH("en", "English"),
    FRENCH("fr", "Français")
}

object LocalizationManager {
    fun getStrings(language: AppLanguage): AppStrings {
        return when (language) {
            AppLanguage.ENGLISH -> EnglishStrings
            AppLanguage.FRENCH -> FrenchStrings
        }
    }
}

data class AppStrings(
    // App Bar & Nav
    val appName: String,
    val dashboard: String,
    val domains: String,
    val calendar: String,
    val statistics: String,
    val reports: String,
    val settings: String,
    val profile: String,
    val goals: String,
    val notifications: String,
    val search: String,
    
    // Auth & Guest Mode
    val welcomeTitle: String,
    val welcomeSubtitle: String,
    val continueAsGuest: String,
    val guestExplanation: String,
    val signInWithGoogle: String,
    val signInWithEmail: String,
    val email: String,
    val password: String,
    val signIn: String,
    val signUp: String,
    val forgotPassword: String,
    val createAccount: String,
    val logout: String,
    val guestAccountNotice: String,
    val migrateDataTitle: String,
    val migrateDataDesc: String,
    val saveAndContinue: String,
    val cancel: String,

    // Dashboard
    val greetingMorning: String,
    val greetingAfternoon: String,
    val greetingEvening: String,
    val todaysProgress: String,
    val completedDomains: String,
    val remainingDomains: String,
    val currentStreak: String,
    val longestStreak: String,
    val days: String,
    val goalProgress: String,
    val quickAdd: String,
    val recentActivities: String,
    val upcomingReminders: String,
    val noRecentActivities: String,
    val noUpcomingReminders: String,

    // Domains
    val searchDomains: String,
    val spiritualDisciplines: String,
    val ddewgTitle: String,
    val ddewgDesc: String,
    val bibleReadingTitle: String,
    val bibleReadingDesc: String,
    val prayerAloneTitle: String,
    val prayerAloneDesc: String,
    val prayerWithOthersTitle: String,
    val prayerWithOthersDesc: String,
    val fastingTitle: String,
    val fastingDesc: String,
    val givingTitle: String,
    val givingDesc: String,
    val accountabilityTitle: String,
    val accountabilityDesc: String,
    val christianLitTitle: String,
    val christianLitDesc: String,
    val christianLitMemTitle: String,
    val christianLitMemDesc: String,
    val bibleMemTitle: String,
    val bibleMemDesc: String,
    val soulWinningTitle: String,
    val soulWinningDesc: String,
    val customDomain: String,
    val addCustomDomain: String,

    // Timer
    val startTimer: String,
    val pauseTimer: String,
    val resumeTimer: String,
    val stopTimer: String,
    val cancelTimer: String,
    val sessionComplete: String,
    val duration: String,
    val activeSessionFound: String,
    val activeSessionPrompt: String,
    val resumeSession: String,
    val endSession: String,
    val discardSession: String,
    val reflectionNotes: String,

    // Forms & Fields
    val save: String,
    val delete: String,
    val edit: String,
    val date: String,
    val bibleVersion: String,
    val bibleBook: String,
    val startChapter: String,
    val endChapter: String,
    val totalChapters: String,
    val prayerType: String,
    val participantsCount: String,
    val participantNames: String,
    val fastingType: String,
    val completeFast: String,
    val partialFast: String,
    val startDate: String,
    val endDate: String,
    val purpose: String,
    val amount: String,
    val givingType: String,
    val tithe: String,
    val offering: String,
    val missions: String,
    val other: String,
    val frequency: String,
    val areasDiscussed: String,
    val bookTitle: String,
    val author: String,
    val totalPages: String,
    val pagesRead: String,
    val preachedTo: String,
    val converted: String,
    val waterBaptized: String,
    val holySpiritBaptized: String,
    val notes: String,

    // Goals
    val spiritualGoals: String,
    val addGoal: String,
    val goalTitle: String,
    val targetValue: String,
    val unit: String,
    val daily: String,
    val weekly: String,
    val monthly: String,
    val targetReached: String,
    val noGoalsYet: String,
    val noGoalsFound: String,

    // Calendar
    val noActivitiesForDate: String,

    // Statistics
    val spiritualAnalytics: String,
    val bibleReading: String,
    val soulWinning: String,
    val totalBibleChapters: String,
    val bibleCompletionRate: String,
    val biblesReadCount: String,
    val totalPrayerTime: String,
    val totalSoulWinning: String,
    val totalFastingDays: String,
    val activityHeatmap: String,
    val analyticsOverview: String,
    val historyAndCalendar: String,
    val totalRecords: String,
    val loggedDisciplineActivities: String,
    val weeklyActivityTrend: String,
    val disciplinesCompletedPerDay: String,
    val biblesRead: String,
    val completion: String,
    val selectedDateLabel: String,
    val allPastRecords: String,
    val timeSpanLabel: String,
    val timesDoneLabel: String,
    val weeklyBreakdownTitle: String,
    val monthlyBreakdownTitle: String,
    val updateProfilePhoto: String,

    // Reports
    val accountabilityReports: String,
    val generatePdf: String,
    val generateReport: String,
    val dailyReport: String,
    val weeklyReport: String,
    val monthlyReport: String,
    val selectDomains: String,
    val allDomains: String,
    val exportPdf: String,
    val shareReport: String,
    val reportHistory: String,
    val generatedHistory: String,
    val noReportHistory: String,
    val pdfGeneratedSuccess: String,

    // Settings
    val appearance: String,
    val theme: String,
    val themeLight: String,
    val themeDark: String,
    val themeSystem: String,
    val language: String,
    val dailyReminders: String,
    val signOut: String,
    val dataManagement: String,
    val cloudBackup: String,
    val cloudRestore: String,
    val lastSynced: String,
    val clearData: String,
    val clearDataConfirm: String,
    val version: String,
    val confirmDelete: String,
    val deleteRecordPrompt: String,

    // Legal & Support
    val privacyPolicy: String,
    val termsConditions: String,
    val supportFeedback: String,

    // Profile & Settings Extra
    val spiritualJourney: String,
    val discipleProfile: String,
    val localAssembly: String,
    val discipleMakerName: String,
    val phoneNumber: String,
    val conversionDate: String,
    val editProfile: String,
    val setDate: String,
    val notSet: String,
    val noActiveReminders: String,
    val addReminderTitle: String,
    val reminderTitleLabel: String,
    val messageLabel: String,
    val hourLabel: String,
    val minuteLabel: String,

    // Reports Extra
    val reportDesc: String,
    val exactDateSelection: String,
    val targetDayLabel: String,
    val weekEndingLabel: String,
    val monthLabel: String,
    val dateRangeLabel: String,
    val changeDate: String,
    val selectDomainsToInclude: String,
    val selectAll: String,
    val generatePdfButton: String,
    val pdfGeneratedTitle: String,
    val openPdf: String,
    val sharePdf: String,
    val shareAccountsTitle: String,
    val shareAccountsDesc: String,
    val shareSummary: String,
    val copyLink: String,

    // Daily Word of Encouragement
    val dailyWordTitle: String,
    val nextQuote: String,
    val dailyQuotes: List<String>
) {
    fun getDomainTitle(key: String): String {
        return when (key) {
            "ddewgTitle" -> ddewgTitle
            "bibleReadingTitle" -> bibleReadingTitle
            "prayerAloneTitle" -> prayerAloneTitle
            "prayerWithOthersTitle" -> prayerWithOthersTitle
            "fastingTitle" -> fastingTitle
            "givingTitle" -> givingTitle
            "accountabilityTitle" -> accountabilityTitle
            "christianLitTitle" -> christianLitTitle
            "christianLitMemTitle" -> christianLitMemTitle
            "bibleMemTitle" -> bibleMemTitle
            "soulWinningTitle" -> soulWinningTitle
            else -> key
        }
    }

    fun getDomainDesc(key: String): String {
        return when (key) {
            "ddewgDesc" -> ddewgDesc
            "bibleReadingDesc" -> bibleReadingDesc
            "prayerAloneDesc" -> prayerAloneDesc
            "prayerWithOthersDesc" -> prayerWithOthersDesc
            "fastingDesc" -> fastingDesc
            "givingDesc" -> givingDesc
            "accountabilityDesc" -> accountabilityDesc
            "christianLitDesc" -> christianLitDesc
            "christianLitMemDesc" -> christianLitMemDesc
            "bibleMemDesc" -> bibleMemDesc
            "soulWinningDesc" -> soulWinningDesc
            else -> key
        }
    }
}

val EnglishStrings = AppStrings(
    appName = "CMFI Accap",
    dashboard = "Home",
    domains = "Domains",
    calendar = "Calendar",
    statistics = "Statistics",
    reports = "Reports",
    settings = "Settings",
    profile = "Profile",
    goals = "Goals",
    notifications = "Notifications",
    search = "Search",

    welcomeTitle = "CMFI Accap Book",
    welcomeSubtitle = "Digital accountability tool for spiritual disciplines and growth in Christian discipleship.",
    continueAsGuest = "Continue as Guest",
    guestExplanation = "You can record all activities locally without an account. Sign in anytime to sync to the cloud.",
    signInWithGoogle = "Sign in with Google",
    signInWithEmail = "Sign in with Email",
    email = "Email Address",
    password = "Password",
    signIn = "Sign In",
    signUp = "Create Account",
    forgotPassword = "Forgot Password?",
    createAccount = "Create Account",
    logout = "Sign Out",
    guestAccountNotice = "You are in Guest Mode (Offline local storage)",
    migrateDataTitle = "Migrate Local Records",
    migrateDataDesc = "Save your local accountability records to your new authenticated account?",
    saveAndContinue = "Save & Continue",
    cancel = "Cancel",

    greetingMorning = "Good Morning",
    greetingAfternoon = "Good Afternoon",
    greetingEvening = "Good Evening",
    todaysProgress = "Today's Progress",
    completedDomains = "Completed",
    remainingDomains = "Remaining",
    currentStreak = "Current Streak",
    longestStreak = "Longest Streak",
    days = "days",
    goalProgress = "Goal Progress",
    quickAdd = "Quick Record",
    recentActivities = "Recent Activities",
    upcomingReminders = "Upcoming Reminders",
    noRecentActivities = "No activities recorded today yet.",
    noUpcomingReminders = "No active reminders scheduled.",

    searchDomains = "Search spiritual disciplines...",
    spiritualDisciplines = "Spiritual Disciplines",
    ddewgTitle = "Daily Dynamic Encounter With God",
    ddewgDesc = "Morning quiet time, scripture meditation, and fellowship with God.",
    bibleReadingTitle = "Bible Reading",
    bibleReadingDesc = "Systematic reading and study of the Scriptures.",
    prayerAloneTitle = "Prayer Alone",
    prayerAloneDesc = "Personal secret place prayer, thanksgiving, and intercession.",
    prayerWithOthersTitle = "Prayer With Others",
    prayerWithOthersDesc = "Corporate prayer, family altar, cell group, and church prayer.",
    fastingTitle = "Fasting",
    fastingDesc = "Abstaining from food or drink for spiritual devotion.",
    givingTitle = "Giving to God",
    givingDesc = "Tithes, offerings, missions, and freewill giving.",
    accountabilityTitle = "Disciple Maker Accountability",
    accountabilityDesc = "Regular reporting and fellowship with your disciple maker.",
    christianLitTitle = "Christian Literature Reading",
    christianLitDesc = "Reading spiritual edifying Christian books.",
    christianLitMemTitle = "Christian Literature Memorization",
    christianLitMemDesc = "Memorizing key excerpts from Christian literature.",
    bibleMemTitle = "Bible Memorization",
    bibleMemDesc = "Hiding God's word in your heart through scripture memory.",
    soulWinningTitle = "Soul Winning",
    soulWinningDesc = "Evangelism, outreach, conversions, and baptisms.",
    customDomain = "Custom Domain",
    addCustomDomain = "Add Custom Domain",

    startTimer = "Start Session",
    pauseTimer = "Pause",
    resumeTimer = "Resume",
    stopTimer = "Stop Session",
    cancelTimer = "Cancel",
    sessionComplete = "Session Complete",
    duration = "Duration",
    activeSessionFound = "Active Session Detected",
    activeSessionPrompt = "An interrupted timer session was found from earlier.",
    resumeSession = "Resume",
    endSession = "Finish & Save",
    discardSession = "Discard",
    reflectionNotes = "Notes & Spiritual Reflection",

    save = "Save Record",
    delete = "Delete",
    edit = "Edit",
    date = "Date",
    bibleVersion = "Bible Version",
    bibleBook = "Book of the Bible",
    startChapter = "Start Chapter",
    endChapter = "End Chapter",
    totalChapters = "Total Chapters",
    prayerType = "Prayer Category",
    participantsCount = "Number of Participants",
    participantNames = "Participant Names (Optional)",
    fastingType = "Fasting Type",
    completeFast = "Complete Fast",
    partialFast = "Partial Fast",
    startDate = "Start Date",
    endDate = "End Date",
    purpose = "Fasting Purpose",
    amount = "Amount",
    givingType = "Giving Type",
    tithe = "Tithe",
    offering = "Offering",
    missions = "Missions",
    other = "Other",
    frequency = "Frequency",
    areasDiscussed = "Areas Discussed",
    bookTitle = "Book Title",
    author = "Author",
    totalPages = "Total Pages",
    pagesRead = "Pages Read",
    preachedTo = "Preached To",
    converted = "Converted",
    waterBaptized = "Water Baptized",
    holySpiritBaptized = "Holy Spirit Baptized",
    notes = "Notes & Insights",

    spiritualGoals = "Spiritual Goals",
    addGoal = "Add Goal",
    goalTitle = "Goal Title",
    targetValue = "Target Amount",
    unit = "Unit",
    daily = "Daily",
    weekly = "Weekly",
    monthly = "Monthly",
    targetReached = "Goal Reached!",
    noGoalsYet = "No goals established yet. Create a goal to track consistency.",
    noGoalsFound = "No goals matching the selected filter.",

    noActivitiesForDate = "No activities recorded for this date.",

    spiritualAnalytics = "Spiritual Analytics",
    bibleReading = "Bible Reading",
    soulWinning = "Soul Winning",
    totalBibleChapters = "Total Bible Chapters Read",
    bibleCompletionRate = "Bible Completion Rate",
    biblesReadCount = "Equivalent Bibles Read",
    totalPrayerTime = "Total Prayer Time",
    totalSoulWinning = "Soul Winning Impact",
    totalFastingDays = "Total Fasting Days",
    activityHeatmap = "Consistency Heatmap",
    analyticsOverview = "Overview Analytics",
    historyAndCalendar = "History & Calendar",
    totalRecords = "Total Records",
    loggedDisciplineActivities = "Logged Discipline Activities",
    weeklyActivityTrend = "Weekly Activity Trend",
    disciplinesCompletedPerDay = "Disciplines completed per day",
    biblesRead = "Bibles Read",
    completion = "Completion",
    selectedDateLabel = "Selected Date",
    allPastRecords = "All Past Accountability Records",
    timeSpanLabel = "Time Span",
    timesDoneLabel = "Times Executed",
    weeklyBreakdownTitle = "Weekly Activities by Day",
    monthlyBreakdownTitle = "Monthly Activities by Week",
    updateProfilePhoto = "Update Profile Photo",

    accountabilityReports = "Accountability Reports",
    generatePdf = "Generate PDF Report",
    generateReport = "Generate Report",
    dailyReport = "Daily Report",
    weeklyReport = "Weekly Report",
    monthlyReport = "Monthly Report",
    selectDomains = "Filter Domains",
    allDomains = "All Domains",
    exportPdf = "Export PDF Document",
    shareReport = "Share Report",
    reportHistory = "Generated Reports History",
    generatedHistory = "Generated Reports",
    noReportHistory = "No PDF reports generated yet.",
    pdfGeneratedSuccess = "PDF Report generated and saved successfully.",

    appearance = "Appearance",
    theme = "Theme Mode",
    themeLight = "Light Theme",
    themeDark = "Dark Theme",
    themeSystem = "System Default",
    language = "Language",
    dailyReminders = "Daily Reminders",
    signOut = "Sign Out",
    dataManagement = "Data & Sync",
    cloudBackup = "Cloud Backup",
    cloudRestore = "Cloud Restore",
    lastSynced = "Last synced",
    clearData = "Clear Local Data",
    clearDataConfirm = "Are you sure you want to delete all local records?",
    version = "App Version",
    confirmDelete = "Confirm Delete",
    deleteRecordPrompt = "Are you sure you want to permanently delete this record?",

    privacyPolicy = "Privacy Policy",
    termsConditions = "Terms & Conditions",
    supportFeedback = "Support & Feedback",

    spiritualJourney = "Spiritual Journey",
    discipleProfile = "Disciple Profile",
    localAssembly = "Local Assembly",
    discipleMakerName = "Disciple Maker Name",
    phoneNumber = "Phone Number",
    conversionDate = "Conversion Date (YYYY-MM-DD)",
    editProfile = "Edit Disciple Profile",
    setDate = "Set Date",
    notSet = "Not set",
    noActiveReminders = "No active reminders set. Add daily alerts for DDEWG or Prayer.",
    addReminderTitle = "Add Spiritual Reminder",
    reminderTitleLabel = "Reminder Title",
    messageLabel = "Message",
    hourLabel = "Hour (0-23)",
    minuteLabel = "Minute (0-59)",

    reportDesc = "Generate a formatted CMFI PDF report summarizing your spiritual disciplines for your Disciple Maker.",
    exactDateSelection = "Exact Date / Date Range Selection:",
    targetDayLabel = "Target Day",
    weekEndingLabel = "Week Ending",
    monthLabel = "Month",
    dateRangeLabel = "Range",
    changeDate = "Change Date",
    selectDomainsToInclude = "Select Exact Domains to Include:",
    selectAll = "Select All",
    generatePdfButton = "Generate %s PDF Report",
    pdfGeneratedTitle = "PDF Generated!",
    openPdf = "Open PDF",
    sharePdf = "Share PDF File",
    shareAccountsTitle = "Share Accounts to Social Media & Messaging",
    shareAccountsDesc = "Send summary links or reports directly to your Disciple Maker, WhatsApp, or Social Platforms:",
    shareSummary = "Share Summary",
    copyLink = "Copy Link",

    dailyWordTitle = "Daily Word of Encouragement (3B Messages)",
    nextQuote = "Next Quote",
    dailyQuotes = listOf(
        "“Return to your first love for the Lord Jesus Christ. This return includes freedom from all sin, freedom from love of self, freedom from love of the world, greed, laziness, and goal-lessness.” — The Bertoua Message (Z.T. Fomum)",
        "“Faithfulness in becoming and being a disciple includes praying alone, daily dynamic encounters with God (DDEWG), Bible reading, reading Christian literature, retreats, fasting, and soul-winning.” — The Pathway to Revival (Z.T. Fomum)",
        "“Son, write on your heart that what a person IS before God is of far greater importance than what he DOES. Seek to be filled with the Holy Spirit in all fullness.” — The Beijing Prophecy (Z.T. Fomum)",
        "“The power released in prayer and fasting depends primarily on WHO is praying and fasting, and secondarily on the duration.” — The Beijing Prophecy (Z.T. Fomum)",
        "“Live your life for the exclusive glory of the Lord Jesus Christ in all things, serving Him in the domain of His call upon your life.” — The Congo Brazzaville Message (Z.T. Fomum)",
        "“During Daily Dynamic Encounters with God (DDEWG), read God's Word, meditate on it, listen to His voice, record what He speaks, and pray it through.” — Pr. Zacharias Tanee Fomum",
        "“When a Spirit-filled believer prays and fasts in total surrender, heaven moves and hell is brought to naught for the glory of Christ!” — 3B Prophetic Messages (Z.T. Fomum)"
    )
)

val FrenchStrings = AppStrings(
    appName = "CMFI Accap",
    dashboard = "Accueil",
    domains = "Domaines",
    calendar = "Calendrier",
    statistics = "Statistiques",
    reports = "Rapports",
    settings = "Paramètres",
    profile = "Profil",
    goals = "Objectifs",
    notifications = "Rappels",
    search = "Recherche",

    welcomeTitle = "Cahier de Redevabilité CMFI",
    welcomeSubtitle = "Outil numérique de redevabilité pour les disciplines spirituelles et la croissance dans le discipulat chrétien.",
    continueAsGuest = "Continuer en tant qu'invité",
    guestExplanation = "Vous pouvez enregistrer toutes vos activités localement sans compte. Connectez-vous à tout moment pour synchroniser.",
    signInWithGoogle = "Se connecter avec Google",
    signInWithEmail = "Se connecter par Email",
    email = "Adresse Email",
    password = "Mot de passe",
    signIn = "Se connecter",
    signUp = "Créer un compte",
    forgotPassword = "Mot de passe oublié ?",
    createAccount = "Créer un compte",
    logout = "Se déconnecter",
    guestAccountNotice = "Mode Invité (Stockage local sur l'appareil)",
    migrateDataTitle = "Migrer les données locales",
    migrateDataDesc = "Enregistrer vos enregistrements locaux dans votre nouveau compte authentifié ?",
    saveAndContinue = "Enregistrer et Continuer",
    cancel = "Annuler",

    greetingMorning = "Bonjour",
    greetingAfternoon = "Bon après-midi",
    greetingEvening = "Bonsoir",
    todaysProgress = "Progrès du Jour",
    completedDomains = "Complétés",
    remainingDomains = "Restants",
    currentStreak = "Série Actuelle",
    longestStreak = "Meilleure Série",
    days = "jours",
    goalProgress = "Progrès des Objectifs",
    quickAdd = "Ajout Rapide",
    recentActivities = "Activités Récentes",
    upcomingReminders = "Prochains Rappels",
    noRecentActivities = "Aucune activité enregistrée aujourd'hui.",
    noUpcomingReminders = "Aucun rappel programmé.",

    searchDomains = "Rechercher des disciplines spirituelles...",
    spiritualDisciplines = "Disciplines Spirituelles",
    ddewgTitle = "Rencontre Dynamique Quotidienne avec Dieu",
    ddewgDesc = "Temps calme du matin, méditation des Écritures et communion avec Dieu.",
    bibleReadingTitle = "Lecture Biblique",
    bibleReadingDesc = "Lecture systématique et étude des Saintes Écritures.",
    prayerAloneTitle = "Prière Seul",
    prayerAloneDesc = "Prière personnelle dans le lieu secret, actions de grâces et intercession.",
    prayerWithOthersTitle = "Prière Avec les Autres",
    prayerWithOthersDesc = "Prière corporative, autel familial, cellule de prière et prière d'église.",
    fastingTitle = "Jeûne",
    fastingDesc = "Abstinence de nourriture ou de boisson pour la dévotion spirituelle.",
    givingTitle = "Offrandes et Libéralités",
    givingDesc = "Dîmes, offrandes, missions et dons volontaires.",
    accountabilityTitle = "Redevabilité au Faiseur de Disciples",
    accountabilityDesc = "Rapports réguliers et communion avec votre faiseur de disciples.",
    christianLitTitle = "Lecture de la Littérature Chrétienne",
    christianLitDesc = "Lecture de livres chrétiens édifiants.",
    christianLitMemTitle = "Mémorisation de la Littérature Chrétienne",
    christianLitMemDesc = "Mémorisation d'extraits clés de la littérature chrétienne.",
    bibleMemTitle = "Mémorisation Biblique",
    bibleMemDesc = "Garder la parole de Dieu dans son cœur par la mémorisation.",
    soulWinningTitle = "Gagnagisme d'Âmes",
    soulWinningDesc = "Évangélisation, témoignage, conversions et baptêmes.",
    customDomain = "Domaine Personnalisé",
    addCustomDomain = "Ajouter un Domaine Personnalisé",

    startTimer = "Démarrer la Session",
    pauseTimer = "Pause",
    resumeTimer = "Reprendre",
    stopTimer = "Arrêter la Session",
    cancelTimer = "Annuler",
    sessionComplete = "Session Terminée",
    duration = "Durée",
    activeSessionFound = "Session Active Détectée",
    activeSessionPrompt = "Une session de minuteur interrompue a été trouvée.",
    resumeSession = "Reprendre",
    endSession = "Terminer et Enregistrer",
    discardSession = "Ignorer",
    reflectionNotes = "Notes & Réflexion Spirituelle",

    save = "Enregistrer",
    delete = "Supprimer",
    edit = "Modifier",
    date = "Date",
    bibleVersion = "Version de la Bible",
    bibleBook = "Livre de la Bible",
    startChapter = "Chapitre de Départ",
    endChapter = "Chapitre de Fin",
    totalChapters = "Total de Chapitres",
    prayerType = "Catégorie de Prière",
    participantsCount = "Nombre de Participants",
    participantNames = "Noms des Participants (Optionnel)",
    fastingType = "Type de Jeûne",
    completeFast = "Jeûne Complet",
    partialFast = "Jeûne Partiel",
    startDate = "Date de Début",
    endDate = "Date de Fin",
    purpose = "Objectif du Jeûne",
    amount = "Montant",
    givingType = "Type de Don",
    tithe = "Dîme",
    offering = "Offrande",
    missions = "Missions",
    other = "Autre",
    frequency = "Fréquence",
    areasDiscussed = "Sujets Abordés",
    bookTitle = "Titre du Livre",
    author = "Auteur",
    totalPages = "Total de Pages",
    pagesRead = "Pages Lues",
    preachedTo = "Personnes Évangélisées",
    converted = "Convertis",
    waterBaptized = "Baptisés d'Eau",
    holySpiritBaptized = "Baptisés du Saint-Esprit",
    notes = "Notes & Enseignements",

    spiritualGoals = "Objectifs Spirituels",
    addGoal = "Ajouter un Objectif",
    goalTitle = "Titre de l'Objectif",
    targetValue = "Valeur Cible",
    unit = "Unité",
    daily = "Quotidien",
    weekly = "Hebdomadaire",
    monthly = "Mensuel",
    targetReached = "Objectif Atteint !",
    noGoalsYet = "Aucun objectif défini. Créez un objectif pour suivre votre régularité.",
    noGoalsFound = "Aucun objectif ne correspond au filtre.",

    noActivitiesForDate = "Aucune activité enregistrée pour cette date.",

    spiritualAnalytics = "Analytique Spirituelle",
    bibleReading = "Lecture Biblique",
    soulWinning = "Gagnagisme d'Âmes",
    totalBibleChapters = "Total Chapitres Bibliques Lus",
    bibleCompletionRate = "Taux de Complétion Biblique",
    biblesReadCount = "Bibles Lues Équivalentes",
    totalPrayerTime = "Temps Total de Prière",
    totalSoulWinning = "Impact du Gagnagisme d'Âmes",
    totalFastingDays = "Jours Totaux de Jeûne",
    activityHeatmap = "Aperçu de la Régularité",
    analyticsOverview = "Vue d'Ensemble Analytique",
    historyAndCalendar = "Historique & Calendrier",
    totalRecords = "Total des Enregistrements",
    loggedDisciplineActivities = "Activités de Discipline Enregistrées",
    weeklyActivityTrend = "Tendance d'Activité Hebdomadaire",
    disciplinesCompletedPerDay = "Disciplines accomplies par jour",
    biblesRead = "Bibles Lues",
    completion = "Complétion",
    selectedDateLabel = "Date Sélectionnée",
    allPastRecords = "Tous les Enregistrements de Redevabilité Passés",
    timeSpanLabel = "Plage Horaire",
    timesDoneLabel = "Nombre de Fois Effectué",
    weeklyBreakdownTitle = "Activités Hebdomadaires par Jour",
    monthlyBreakdownTitle = "Activités Mensuelles par Semaine",
    updateProfilePhoto = "Mettre à jour la Photo de Profil",

    accountabilityReports = "Rapports de Redevabilité",
    generatePdf = "Générer Rapport PDF",
    generateReport = "Générer le Rapport",
    dailyReport = "Rapport Journalier",
    weeklyReport = "Rapport Hebdomadaire",
    monthlyReport = "Rapport Mensuel",
    selectDomains = "Filtrer les Domaines",
    allDomains = "Tous les Domaines",
    exportPdf = "Exporter en Document PDF",
    shareReport = "Partager le Rapport",
    reportHistory = "Historique des Rapports",
    generatedHistory = "Rapports Générés",
    noReportHistory = "Aucun rapport PDF généré.",
    pdfGeneratedSuccess = "Rapport PDF généré et enregistré avec succès.",

    appearance = "Apparence",
    theme = "Mode de Thème",
    themeLight = "Thème Clair",
    themeDark = "Thème Sombre",
    themeSystem = "Thème du Système",
    language = "Langue",
    dailyReminders = "Rappels Quotidiens",
    signOut = "Se Déconnecter",
    dataManagement = "Données & Synchronisation",
    cloudBackup = "Sauvegarde Nuage",
    cloudRestore = "Restauration Nuage",
    lastSynced = "Dernière synchro",
    clearData = "Effacer les Données Locales",
    clearDataConfirm = "Êtes-vous sûr de vouloir supprimer tous les enregistrements locaux ?",
    version = "App Version",
    confirmDelete = "Confirmer la Suppression",
    deleteRecordPrompt = "Êtes-vous sûr de vouloir supprimer définitivement cet enregistrement ?",

    privacyPolicy = "Politique de Confidentialité",
    termsConditions = "Conditions Générales",
    supportFeedback = "Support & Commentaires",

    spiritualJourney = "Parcours Spirituel",
    discipleProfile = "Profil du Disciple",
    localAssembly = "Assemblée Locale",
    discipleMakerName = "Nom du Faiseur de Disciples",
    phoneNumber = "Numéro de Téléphone",
    conversionDate = "Date de Conversion (AAAA-MM-JJ)",
    editProfile = "Modifier le Profil du Disciple",
    setDate = "Définir la Date",
    notSet = "Non défini",
    noActiveReminders = "Aucun rappel actif. Ajoutez des alertes quotidiennes pour la RDQD ou la Prière.",
    addReminderTitle = "Ajouter un Rappel Spirituel",
    reminderTitleLabel = "Titre du Rappel",
    messageLabel = "Message",
    hourLabel = "Heure (0-23)",
    minuteLabel = "Minute (0-59)",

    reportDesc = "Générez un rapport PDF formaté CMFI résumant vos disciplines spirituelles pour votre faiseur de disciples.",
    exactDateSelection = "Sélection de Date / Plage de Dates :",
    targetDayLabel = "Jour Cible",
    weekEndingLabel = "Fin de Semaine",
    monthLabel = "Mois",
    dateRangeLabel = "Période",
    changeDate = "Changer la Date",
    selectDomainsToInclude = "Sélectionnez les Domaines à Inclure :",
    selectAll = "Tout Sélectionner",
    generatePdfButton = "Générer Rapport PDF %s",
    pdfGeneratedTitle = "PDF Généré !",
    openPdf = "Ouvrir le PDF",
    sharePdf = "Partager le Fichier PDF",
    shareAccountsTitle = "Partager les Comptes sur les Réseaux Sociaux & Messageries",
    shareAccountsDesc = "Envoyez des résumés ou rapports directement à votre faiseur de disciples, WhatsApp, ou réseaux sociaux :",
    shareSummary = "Partager le Résumé",
    copyLink = "Copier le Lien",

    dailyWordTitle = "Parole d'Encouragement Quotidienne (Messages 3B)",
    nextQuote = "Citation Suivante",
    dailyQuotes = listOf(
        "« Retourne à ton premier amour pour le Seigneur Jésus-Christ. Ce retour inclut la libération de tout péché, de l'amour de soi, de l'amour du monde, de la cupidité, de la paresse et du manque de buts. » — Le Message de Bertoua (Z.T. Fomum)",
        "« La fidélité à devenir et rester un disciple inclut la prière seul, la rencontre dynamique quotidienne avec Dieu (RDQD), la lecture biblique, la littérature chrétienne, les retraites, le jeûne et le gagnagisme d'âmes. » — Le Chemin de la Revivification (Z.T. Fomum)",
        "« Mon fils, écris sur ton cœur que ce qu'une personne EST devant Dieu est de bien plus grande importance que ce qu'elle FAIT. Cherche à être rempli du Saint-Esprit en toute plénitude. » — La Prophétie de Pékin (Z.T. Fomum)",
        "« La puissance libérée dans la prière et le jeûne dépend principalement de QUI prie et jeûne, et secondairement de la durée. » — La Prophétie de Pékin (Z.T. Fomum)",
        "« Vis ta vie pour la gloire exclusive du Seigneur Jésus-Christ en toutes choses, en Le servant dans le domaine de Son appel sur ta vie. » — Le Message de Congo Brazzaville (Z.T. Fomum)",
        "« Pendant la Rencontre Dynamique Quotidienne avec Dieu (RDQD), lis la Parole de Dieu, médite-la, écoute Sa voix, note ce Qu'Il dit, et prie en conséquence. » — Pr. Zacharias Tanee Fomum",
        "« Quand un croyant rempli de l'Esprit prie et jeûne dans un abandon total, le ciel se meut et l'enfer est réduit à néant pour la gloire du Christ ! » — Messages Prophétiques 3B (Z.T. Fomum)"
    )
)
